load('//Config:configs.bzl', 'library_configs', 'info_plist_substitutions', 'app_binary_configs')
load('//Config:buck_rule_macros.bzl', 'first_party_library')

first_party_library(
    name = 'NetworkingAPI',
    visibility = [
        'PUBLIC',
    ],
    swift_version = '5',
    deps = [
    ],
)