load('//Config:configs.bzl', 'library_configs', 'info_plist_substitutions', 'app_binary_configs')
load('//Config:buck_rule_macros.bzl', 'first_party_library')

first_party_library(
    name = 'Utilities',
    visibility = [
        'PUBLIC',
    ],
    swift_version = '5',
    deps = [
    ],
    test_deps = [
        ':Stubs',
        '//Libraries/NetworkingMock:NetworkingMock',
    ],
)

apple_resource(
    name = 'Stubs',
    files = glob([
        '**/*.png',
    ]),
)
